import type { Metadata } from "next";
import { Nunito_Sans as NunitoSans } from "next/font/google";
import { headers } from "next/headers";
import { getHostConfig } from "@/services/host-service";
import { CSSProperties } from "react";
import "./globals.css";

const nunitoSans = NunitoSans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const hostName = headerList.get("x-host-name") || "";

  const host = await getHostConfig(hostName);

  const dynamicStyles = {
    "--color-main-50": host.theme.main50,
    "--color-main-100": host.theme.main100,
    "--color-main-200": host.theme.main200,
    "--color-main-300": host.theme.main300,
    "--color-main-400": host.theme.main400,
    "--color-main-500": host.theme.main500,
    "--color-main-600": host.theme.main600,
    "--color-main-700": host.theme.main700,
    "--color-main-800": host.theme.main800,
    "--color-main-900": host.theme.main900,
    "--color-main-950": host.theme.main950,
    "--color-gray-50": host.theme.gray50,
    "--color-gray-100": host.theme.gray100,
    "--color-gray-200": host.theme.gray200,
    "--color-gray-300": host.theme.gray300,
    "--color-gray-400": host.theme.gray400,
    "--color-gray-500": host.theme.gray500,
    "--color-gray-600": host.theme.gray600,
    "--color-gray-700": host.theme.gray700,
    "--color-gray-800": host.theme.gray800,
    "--color-gray-900": host.theme.gray900,
    "--color-gray-950": host.theme.gray950,
  } as CSSProperties;

  return (
    <html
      lang="en"
      className={`${nunitoSans.variable} h-full antialiased`}
      style={dynamicStyles}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
